version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: booktable_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
