version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: booktable_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  pgadmin:
    container_name: booktable_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ducnhatphung@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
